### ISSUE TITLE
Improve player count

### ISSUE THREAD

**Issue by Cyber-Samurai-997** [seDirector/App#19]
**Describe the bug**
seDirector showing players connected to the server incorrectly, sometime even showed players on the server while there wasn't any.

**Screenshot with Source Admin Tool for comparison:**
![image](https://user-images.githubusercontent.com/66083398/136500245-2dcd1ebd-d587-4c2d-b838-ae4dfcac5ffa.png)
![unknown](https://user-images.githubusercontent.com/66083398/136500301-e005ff6d-2d83-4229-91fe-129785a48542.png)
![image](https://user-images.githubusercontent.com/66083398/136505615-8d239cab-c92e-4998-9dcc-2b15a92a05cb.png)

**Desktop**
 - OS: [Window 10 Pro v21H1 build 19043.1237]
 - Browser: OperaGX
 - seDirector Version 6.12.1.0

**Additional context**
It's maybe counting both bot and players controlled survivors/infected.

**Comment by Cyber-Samurai-997** [comment]
Lol, great to hear that!

**Comment by asheroto** [comment]
This has been completed and live.

**Comment by Cyber-Samurai-997** [comment]
Great work!
