### ISSUE TITLE
Bug interface with translation from other languages

### ISSUE THREAD

**Issue by crashzk** [seDirector/App#4]
Using the **Portuguese-B**R translation in seDirector some fields are buggy in the program interface, here are some prits:

![image](https://user-images.githubusercontent.com/32937653/135770460-3d58215a-a2df-49d8-bb74-67f53f1fab8a.png)

![image](https://user-images.githubusercontent.com/32937653/135770513-5ebd372a-b0a7-44ae-aae7-e37d6635b62f.png)

![image](https://user-images.githubusercontent.com/32937653/135770803-17f5ca69-746c-4f3f-9b7f-bb1618923c30.png)

**Comment by asheroto** [comment]
Thank you, I believe I fixed this.  It will be fixed in the next release.
