### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by crashzk** [seDirector/App#40]
I believe it is a bug, better, just a lack of translation. It wouldn't be a big problem but I think it's good to let you know.

Everything is translated except this option/information:
![image](https://user-images.githubusercontent.com/32937653/151022727-c879aee6-b04a-4dd1-b9b0-77f36ff42000.png)

**Comment by asheroto** [comment]
Thanks for reporting this. I have fixed it and it will be available in the next version.
