### ISSUE TITLE
Application may freeze under certain conditions (remove QueryMaster)

### ISSUE THREAD

**Issue by asheroto** [seDirector/App#43]

**Comment by crashzk** [comment]
**@asheroto** I don't know if the error would be that, but for me after a while with the application open running the server it just freezes.

![image](https://user-images.githubusercontent.com/32937653/161893484-89f91f9a-fc3b-4188-997c-a19d13edd142.png)

Server is running normally, but the application can not change anything, or minimize or click on any option.

Could it be the same problem?

I'm running version **6.17.0.0**.
