### ISSUE TITLE
"Pending Restart Bug"

### ISSUE THREAD

**Issue by DAYBR3AK1999** [seDirector/App#70]
**Description**
Whenever a scheduled restart is done it does not force close the game server.

**To Reproduce**
At the 5 in the morning scheduled restart, some server keep being stuck on "Pending restart".
No errors received nor in logs nor on discord.

**Expected behavior**
Just restart the game server as scheduled.

**Screenshots**
![1](https://github.com/seDirector/App/assets/44482339/c81860ec-880d-4b4b-b0c0-93c39933db22)
![2](https://github.com/seDirector/App/assets/44482339/37ac88eb-0b14-46c9-8266-fff13ea1b928)
![3](https://github.com/seDirector/App/assets/44482339/72febdf4-c917-4abb-87f0-29c9d3817aa4)
![4](https://github.com/seDirector/App/assets/44482339/1766de53-08ce-4025-9b1e-c2adf0739961)
![5](https://github.com/seDirector/App/assets/44482339/d68243ae-f425-4f3c-a53b-9d3a3d8e7214)
![6](https://github.com/seDirector/App/assets/44482339/1282b956-76d5-4591-8441-de9b8799c8e5)
![7](https://github.com/seDirector/App/assets/44482339/587ee2ec-ba45-409b-8161-728d2f589ded)
![8](https://github.com/seDirector/App/assets/44482339/9001b1cc-bce2-4b99-9cff-7e2404f0c20c)
![9](https://github.com/seDirector/App/assets/44482339/97277632-699b-4051-a3cd-c0337c9f0c20)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: N/A
 - Version: 7.2.5.0

**Additional context**
After a check with Asheroto & SkyWalker3200 it seems to be an issue with forced closing of a Windows Task.

**Comment by asheroto** [comment]
Fixed in version 7.3.0, pending beta tests.
