### ISSUE TITLE
[Feature Request]: Option to use srcds_win64

### ISSUE THREAD

**Issue by MishaMorozko** [seDirector/App#90]
### Checklist

- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this issue is not security related. 
- [X] I have verified that the latest version of [.NET
Framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework)
has been installed.

- [X] I have restarted my computer to confirm this is not a transitory
problem.

### What You Are Seeing?

Currently, when a TF2 server is installed/added, seDirector uses srcds executable. An update on April 18, 2024 added support for 64bit systems.

### What is Expected?

There should be a toggle to use either 32bit or 64bit version.

### How Did You Get This To Happen?

![Screenshot 2024-06-28 185041](https://github.com/seDirector/App/assets/148559940/3d67ad9d-97e4-45a9-ab2c-761a3d3df913)
As it shows, the option to change server executable is locked, and the user can only choose the folder where srcds exists, not choose the executable itself

### System Details

- Windows 11 Pro
- seDirector 7.4.4.0 Free

### Additional Context

There's an untested workaround where I could change executable file name and trick seDirector.
Perhaps going to give it a try and update with results.

**Comment by asheroto** [comment]
This will definitely be added, thanks!

**Comment by asheroto** [comment]
This has been added in the upcoming version `7.5.0` which should be released this week.
