### ISSUE TITLE
[Bug]: Sourcemod Translations Folder reset

### ISSUE THREAD

**Issue by Geheim123** [seDirector/App#94]
### Checklist

- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this issue is not security related. 
- [X] I have verified that the latest version of [.NET
Framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework)
has been installed.

- [X] I have restarted my computer to confirm this is not a transitory
problem.

### What You Are Seeing?

After an Upgrade/Downgrade the Translation Folder gets resetted (plugin files/own Files etc gets deleted except the Files that come with Sourcemod))

### What is Expected?

No deleted Files

### How Did You Get This To Happen?

Upgrade/Downgrade Sourcemod

### System Details

Win 11 - SeDirector 7.5.0.3

**Comment by asheroto** [comment]
This issue will be fixed in version `7.5.1`.
