### ISSUE TITLE
[Bug]: TF2 - srcds_win64 Show/Hide Button for console not working

### ISSUE THREAD

**Issue by Geheim123** [seDirector/App#95]
### Checklist

- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this issue is not security related. 
- [X] I have verified that the latest version of [.NET
Framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework)
has been installed.

- [X] I have restarted my computer to confirm this is not a transitory
problem.

### What You Are Seeing?

Cannot Collapse/expand the console with the Show/Hide Button with the srcds_win64.exe.
the 32bit version is working.

### What is Expected?

Collapse/expand the console with the Show/Hide Button

### How Did You Get This To Happen?

Choose the srcds_win64.exe as your SRCDS Location > Save
Start the Server and try to use the Show/Hide Button.

### System Details

Win 11 SeDirector 7.5.0.3

**Comment by asheroto** [comment]
This issue will be resolved in version `7.5.1`.
